# Generated by Django 3.0.5 on 2022-01-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='teams')),
                ('name', models.TextField(max_length=100)),
                ('designation', models.TextField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='slideshow',
            old_name='slideshow_img',
            new_name='img',
        ),
    ]
